/*Nova estrutura usando normalizações*/
CREATE TABLE alunos(
	matricula_aluno int(11) NOT NULL AUTO_INCREMENT,
	nome_aluno int(11) COLLATE utf8_general_mysql500_ci NOT NULL,
	escolaridade_aluno int(11) COLLATE utf8_general_mysql500_ci NOT NULL,
	telefone_aluno int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	nome_mae int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	telefone_mae int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	nome_pai int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	telefone_pai int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	responsavel_pagamento varchar(500) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	desconto int(11) DEFAULT NULL,
	foto_aluno int(11) COLLATE utf8_general_mysql500_ci NOT NULL DEFAULT 'img/fotos/default.png',
	cep_endereco int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	endereco_completo int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	numero_endereco int(11) DEFAULT NULL,
	bairro_endereco int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	cidade_endereco int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	estado_endereco int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	complemento_endereco int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	cupom_desconto int(11) COLLATE utf8_general_mysql500_ci DEFAULT NULL,
	descricao_aluno int(11) COLLATE utf8_general_mysql500_ci DEFAULT 'NOT DEFINED',
	PRIMARY KEY (matricula_aluno),
	FOREIGN KEY (nome_aluno)REFERENCES nome_alunos(id_matricula_aluno),
	FOREIGN KEY (escolaridade_aluno)REFERENCES escolaridade_alunos(id_escolaridade),
	FOREIGN KEY (telefone_aluno)REFERENCES telefone_alunos(id_telefone),
	FOREIGN KEY (nome_mae)REFERENCES mae_alunos(id_mae),
	FOREIGN KEY (telefone_mae)REFERENCES telefone_mae_alunos(id_telefone_mae),
	FOREIGN KEY (nome_pai)REFERENCES pai_alunos(id_pai),
	FOREIGN KEY (telefone_pai)REFERENCES telefone_pai_alunos(id_telefone_pai),
	FOREIGN KEY (responsavel_pagamento)REFERENCES responsavel_pagamento_alunos(id_responsavel),
	FOREIGN KEY (desconto)REFERENCES desconto_alunos(id_desconto),
	FOREIGN KEY (foto_aluno)REFERENCES foto_alunos(id_foto),
	FOREIGN KEY (cep_endereco)REFERENCES cep_alunos(id_matricula_aluno),
	FOREIGN KEY (endereco_completo)REFERENCES endereco_alunos(id_matricula_aluno),
	/*FOREIGN KEY (numero_endereco)REFERENCES endereco_alunos(id_matricula_aluno),
	FOREIGN KEY (bairro_endereco)REFERENCES endereco_alunos(id_matricula_aluno),
	FOREIGN KEY (cidade_endereco)REFERENCES endereco_alunos(id_matricula_aluno),
	FOREIGN KEY (estado_endereco)REFERENCES endereco_alunos(id_matricula_aluno),
	FOREIGN KEY (complemento_endereco)REFERENCES endereco_alunos(id_matricula_aluno),*/
	FOREIGN KEY (cupom_desconto)REFERENCES cupons_desconto(id_matricula_aluno),
	FOREIGN KEY (descricao_aluno)REFERENCES descricao_alunos(id_matricula_aluno);	
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_mysql500_ci;